### ISSUE TITLE
Error with certain text files

### ISSUE THREAD

**Issue by marcelolafleur** [simone-mordue/InferSDGs#1]
I was testing the app and ran into an odd error. With some files, I get the error: 
`> ggplot(all, aes(y=Value, x=ID)) + 
+   geom_col(fill=all$colour)+
+   coord_flip()+
+   theme_classic()+
+   xlab("Mean SDGs")+
+   ylab("Proportion fit")
Error: Aesthetics must be either length 1 or the same as the data (68): fill`

I'm attaching one of these files here. It doesn't seem related to line endings or encoding, but I didn't test it extensively. 

The odd thing is that it only happens when both "marine.txt" and "poverty.txt" are also present, so the file itself isn't the problem. Very odd. Let me know if I can help debut it more.

[W2006_crlf.txt](https://github.com/simone-mordue/InferSDGs/files/6488530/W2006_crlf.txt)

**Comment by simone-mordue** [comment]
This was to do with the ggplot function not recognizing how many files were read in. I have adjusted the code so it works now.
